24| jobs:
25|   create_nuget:
26|     runs-on: ubuntu-latest
27|     steps:
28|     - uses: actions/checkout@v3
29|       with:
30|         fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
31| 
32|     # Install the .NET SDK indicated in the global.json file
33|     - name: Setup .NET
34|       uses: actions/setup-dotnet@v4
35| 
36|     # Ensure the NuGet output directory exists
37|     - name: Create NuGet output directory
38|       run: mkdir -p ${{ env.NuGetDirectory }}
39| 
40|     - name: Build EasyRequestHandler
41|       run: dotnet build src/RequestHandlers.csproj --configuration Release
42| 
43|     - name: Create NuGet package
44|       run: dotnet pack src/RequestHandlers.csproj --configuration Release --output ${{ env.NuGetDirectory }}
45|     
46|     # Publish the NuGet package as an artifact
47|     - uses: actions/upload-artifact@v3
48|       with:
49|         name: nuget
50|         if-no-files-found: error
51|         retention-days: 7
52|         path: ${{ env.NuGetDirectory }}/*.nupkg
